//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SiamDev2012Entities1 : DbContext
    {
        public SiamDev2012Entities1()
            : base("name=SiamDev2012Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hisOpcionesProcs> hisOpcionesProcs { get; set; }
        public virtual DbSet<hisTiposOpc> hisTiposOpc { get; set; }
    
        public virtual ObjectResult<prcHCObtenerOpcionesDatos_Result> prcHCObtenerOpcionesDatos(string strOpcTipo)
        {
            var strOpcTipoParameter = strOpcTipo != null ?
                new ObjectParameter("strOpcTipo", strOpcTipo) :
                new ObjectParameter("strOpcTipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcHCObtenerOpcionesDatos_Result>("prcHCObtenerOpcionesDatos", strOpcTipoParameter);
        }
    
        public virtual ObjectResult<prcHCObtenerOpcionesDatos_Result> ObtenerOpcionesDatos(string strOpcTipo)
        {
            var strOpcTipoParameter = strOpcTipo != null ?
                new ObjectParameter("strOpcTipo", strOpcTipo) :
                new ObjectParameter("strOpcTipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcHCObtenerOpcionesDatos_Result>("ObtenerOpcionesDatos", strOpcTipoParameter);
        }
    }
}
