//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hisOpcionesProcs
    {
        public short opcNumero { get; set; }
        public string opcTipo { get; set; }
        public string opcCodigo { get; set; }
        public string opcNombre { get; set; }
        public bool opcInactivo { get; set; }
        public string opcCodGral { get; set; }
        public int opcOrden { get; set; }
        public byte opcTipoOpcion { get; set; }
        public string opcParametro { get; set; }
    
        public virtual hisTiposOpc hisTiposOpc { get; set; }
    }
}
