//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hisTiposOpc
    {
        public hisTiposOpc()
        {
            this.hisOpcionesProcs = new HashSet<hisOpcionesProcs>();
        }
    
        public string tipCodigo { get; set; }
        public string tipNombre { get; set; }
        public byte tipTipo { get; set; }
    
        public virtual ICollection<hisOpcionesProcs> hisOpcionesProcs { get; set; }
    }
}
